yalelibrary/yul-dc-camerata

- .env
- .env.ecs
- docker-compose.yml
As we try to consolidate configs, it's been difficult to figure out where
a particular value is being set based on multiple instances of enviroment
settings and the corresponding order of precedence.
As a first step, this PR brings all the enviroment into docker-compose.yml
so that we have a single file to manage.  Once we have working local and
ECS settings, we can revisit which settings it makes sense to manage via
separate config files.
> Move all environment variable setup into compose file

- docker-compose.ecs.yml
Sets the passenger environment to `production` for the blacklight and management apps. This is WIP because it depends on the blacklight and management app having secret_key_base set up.
> WIP Rails in production on ecs

- docker-compose.ecs.yml
We have discovered additional changes required to run sucessfully in production mode.
This commit reverts the initial attempt until we have more of the configurations
tested and working.
> Revert the changes made by PR #37

- base/Dockerfile
- base/README.md
- base/docker-compose.yml
This will allow us to use a single more uniform base across projects
and rely on Dockers caching and layer system to speed up and solidy
our build and deployment processes.
> Add Yul-base Dockerfile to coordinate a base across projects

- .rspec
- .rubocop.yml
- Gemfile
- Gemfile.lock
- README.md
- spec/deploy_spec.rb
- spec/spec_helper.rb
Rspec suite tests that a local or deployed YUL-DC cluster 
* has a blacklight app with a language facet, at least 40 search results, and Universal Viewer for a public object but not a yale-only object
* has a manifest service that delivers some parseable manifests
* has a iiif image service that delivers a parseable info.json  (https://github.com/yalelibrary/YUL-DC/issues/230)
> Test local or deployed blacklight

- Gemfile.lock
- docker-compose.ecs.yml
- docker-compose.yml
v2.0.0 of the manifest service https://github.com/yalelibrary/yul-dc-iiif-manifest will require the IIIF_IMAGE_BASE_URL and IIIF_MANIFESTS_BASE_URL to be set for the discovery app to display images in both production and development environments.
Preliminary work connected to https://github.com/yalelibrary/YUL-DC/issues/237
> Prepare for manifest service v.2.0.0

- docker-compose.ecs.yml
- docker-compose.yml
* Allow deployment scripts to pass `RAILS_MASTER_KEY` set in the local environment
* Set `PASSENGER_APP_ENV` & `RAILS_ENV` to production in running containers
* Change database configurations to reference production
> Configure camerata to run containers in Rails production mode on ECS

- .circleci/config.yml
- spec/deploy_spec.rb
Use tag ci_pending for tests not yet working in CI but known to work 
against development and deployed environments.
> Mark pending specs separately for CI

- docker-compose.yml
- secrets-template
Use either `.secrets` or locally set environment variables to
pass Honeybadger API keys for exception reporting.
HONEYBADGER_API_KEY_BLACKLIGHT
HONEYBADGER_API_KEY_MANAGEMENT
> Pass Honeybadger API Keys to ECS clusters

- README.md
- spec/deploy_spec.rb
- Documents usage of basic auth credentials in deployment test suite.
- Adds configuring of test suite's blacklight basic auth credentials via .secrets file if it exists
- Provides messaging on what credentials are being used and if credentials were set via secrets file
Relates to #256
> Improve password management for tests

- README.md
- bin/deploy-full.sh
- bin/shared-checks.sh
The RAILS_MASTER_KEY is used to decrypt encoded credentials checked into
the yul-dc-blacklight and yul-dc-management repos.  We have agreed to use
the same credentials for both repos and to share the encryption key out-of-band
with team members.
The key must be a 32-character hex string representing a 16-byte encoding key.
The key must be set in the shell environment of the machine running the `deploy-full.sh`
script.
For more details see https://edgeguides.rubyonrails.org/security.html#environmental-security
> Add a deployment check for the RAILS_MASTER_KEY

- .circleci/config.yml
- spec/deploy_spec.rb
Moves to a machine based approach on Circle. This is slightly slower, but in the Camerata case, not significantly so (it costs about 30s on average in my testing). The advantages are a few fold:
- No duplication between docker-compose.yml and .circleci/config
- Read from the same place for getting current versions of the upstream images as running locally does. This means no more syncing vars to CircleCI's project repo. Even though that command line tool made it easy, it was a manual step and going to get forgotten.
- ENV vars (both locally and via context/project) can be properly sent in to all the containers, not just the primary one. Even if we got around `RAILS_MASTER_KEY`, the **AWS** keys were a show stopper for all our other approaches on this.
- SSH debugging is much easier in CI, …
> Move CircleCI to be DockerCompose Based To Mimic Local Smoke Test Runs

- smoke_spec/deploy_spec.rb
- templates/blacklight-compose.yml
- templates/db-compose.yml
- templates/iiif-images-compose.ecs.yml
- templates/iiif-images-compose.yml
- templates/iiif-manifest-compose.yml
- templates/management-compose.yml
- templates/solr-compose.yml
Also added check to the deploy tests that the blacklight and management front pages are displaying version numbers.
> Provide version numbers to containers through gem

- lib/camerata.rb
Co-authored by Rob Kaufman <rob.kaufman@notch8.com>
- Users in the blacklight repo can run the management app
- Users in the management repo can run the blacklight app
- `cam logs <app>` is now an available command
> Fixed the logging and code mounting issues

- .gitignore
- README.md
- bin/add-alb.sh
- bin/build-cluster.sh
- bin/deploy-main.sh
- bin/deploy-psql.sh
- bin/deploy-solr.sh
- bin/get-params.sh
- docker-compose.ecs.yml
- templates/blacklight-compose.ecs.yml
- templates/management-compose.ecs.yml
* use cluster-specific private domains, resolves "too many overlapping
zones" problem
* set assign_public_ip function based on whether in Yale, or DCE env
* ignore vendored gems in .gitignore
* uses default security group in the DCE cases
* export PUBLIC_IP to get-params when called from other scripts
> Updates to merge Yale & DCE deployments

- smoke_spec/deploy_spec.rb
Related to https://github.com/yalelibrary/yul-dc-management/pull/220 and https://github.com/yalelibrary/YUL-DC/issues/460
This doesn't resolve the concern mentioned in https://github.com/yalelibrary/yul-dc-camerata/pull/127 of the yale-only test object being unavailable in environments with Yale VPN access, but I think that'll be ok until tomorrow.
> Make smoke tests pass on the small seed dataset

- smoke_spec/deploy_spec.rb
Styling changes in yul-dc-blacklight v1.14.0 resulted in spurious smoke test failure.  Finding the link by ID without checking for its text to make the test less fragile.
> Refactor test for manifest link from blacklight

- lib/camerata.rb
- lib/camerata/parameters.rb
- lib/camerata/secrets.rb
- spec/camerata_cli_spec.rb
- spec/camerata_env_spec.rb
- spec/camerata_parameters_spec.rb
Refactors the env_copy method and specs:
- Establishes a subroutine for creating param names
- Establishes a subroutine for copying string parameters
> Fix secrets copy from default ns

- .circleci/config.yml
* Run the local-development smoke tests in the scheduled workflow only
* Increase the startup delay the local-development smoke tests tolerate
* Run the specs and style checks for the gem code in the commit workflow only
> Separate the gem tests from the local-development integration test

- templates/management-compose.ecs.yml
- templates/management-compose.yml
- This will continue to change with namespacing environment variables in AWS SSM
> Using environment vars for metadata cloud host

- Gemfile.lock
- smoke_spec/deploy_spec.rb
- smoke_spec/spec_helper.rb
Check for at least five pages of search results in deployed 
environments.  Remove unused "deployed" variable.
> Match local-mode smoke test to seeds

- bin/deploy-main.sh
This PR increase the timeout for deploy-main to 10 minutes. Yale's cluster deployment will sometime surpass the default 5 minute timeout causing Jenkins deployment to fail.
>  Update timeout interval to 10 minutes

- lib/camerata/cluster.rb
Add METADATA_CLOUD_HOST to the list of parameter store variables Camerata looks for
> Pull METADATA_CLOUD_HOST from parameter store

- .circleci/config.yml
- smoke_spec/deploy_spec.rb
* Disable private-item test which passes for the wrong reason
* Separate versions of open-search test when deployed tag is true vs.
when deployed tag is false
* Skip local-only tests in continuous-deploy scheduled CircleCI job
* Skip deployed-only tests in local-mode scheduled CircleCI job
Co-Authored-By: Max Kadel <max@curationexperts.com>
> Make local-mode smoke test pass if only one item is seeded

- smoke_spec/deploy_spec.rb
Context:  the smoke tests look for a language facet as a proxy for "are facets rendering on the front page".  But the single item that is being seeded when the management app first spins up doesn't have language metadata because it's a pen rather than a book or document.  Changing that test, in local mode, to check for one of the facets that does get populated with that ultra-minimal seed set.  ("format")
> Make local-mode smoke test check for a facet the seed item supports

- smoke_spec/deploy_spec.rb
The smoke specs for management need to temporarly check only that the front page responds and prompts for a user login. Later, when we have a CAS account we can use for this purpose, we can restore some more sophisticated smoke testing here.
> Update smoke specs for management now that CAS auth is in place

- templates/management-compose.local.yml
- Separate this PR from cleanup PR
PASSENGER_APP_ENV=production cam up management
You'll then need to make the database with cam exec management bash -l -c 'RAILS_ENV=production rails db:create db:schema:load db:seed'
> Management can be run in prod mode locally

- .circleci/config.yml
Future work: run local-mode scheduled check pulling parameters from Yale 
AWS; run scheduled deploys against a continuous deploy cluster on yale 
infrastructure.
> Disable scheduled CI jobs

- templates/blacklight-compose.ecs.yml
- templates/management-compose.ecs.yml
This PR removed hard-coded urls for IIIF_MANIFEST_BASE_URL and IIIF_IMAGE_BASE_URL, so we can get values from AWS SSM Parameter store. 
Connected to: https://github.com/yalelibrary/YUL-DC/issues/630
> remove hardcoded urls

- bin/build-cluster.sh
- bin/deploy-worker.sh
- bin/get-params.sh
* now creates $cluster-worker-params.yml in get-params and
create-cluster
t2.large instance parameters sized to allow for 2 tasks, or 1 task + a deploy
> Updates to camerata parameter scripts

- base/Dockerfile
- base/README.md
- lib/camerata/secrets.rb
This PR adds Dynatrace OneAgent to the Camerata Base Image, bumps the Image version to 1.1.0 and adds instructions for OneAgent integration
> Add Dynatrace OneAgent to Camerata Base

- bin/create-continst.sh
Updated Dynatrace install script to use token variable in ssm and added "--set-host-name" option. We also removed public IP by removing "--associate-public-ip-address" when creating the EC2 instance.
> update install script for Dynatrace client

- templates/worker-compose.yml
* set WORKER_COUNT shell variable to control # of workers spawned by
delayed job
* defaults to 1 process if unset
> Add ability to control number of worker processes for dj

- templates/management-compose.ecs.yml
This sets the command for the management container.
The default was "/sbin/my_init" prior to this change.
This PR follows the pattern used in the blacklight container command which first creates the DEPLOYED_AT file and then runs the prior default command.
> Adds DEPLOYED_AT file to management containers in ECS

- README.md
- moved the release steps for all apps into this readme as discussed a month or two ago
- detail how to do a release of the master branch with version numbers
- detail how to deploy an individual branch to test
- does not mention the manifest or iiif apps since those will be deleted
> Update deployment instructions to work for all apps

- bin/deploy-worker.sh
- bin/get-params.sh
Deploy-worker.sh was re-fetching params if ecs-params.yml didn't exist, but get-params doesn't create ecs-params anymore.
> Deploy worker using existing worker-params.yml

- bin/create-continst.sh
Up dated the bin/create-continst.sh script to create a launch template and auto-scaling group for the container instances. This will allow us to more easily scale up the number the ec2 instances needed for our worker  tasks. We can also take advantage of ECS capacity providers that will automatically scale up or down the number EC2 instances based on the amount of tasks we launch.
> Worker asg

- bin/update-continsh.sh
Mount Goobi non brbl network shares to worker nodes.
> Add goobi non-brbl mounts

- templates/management-compose.ecs.yml
- templates/management-compose.yml
Moves activejob:schedule command from main to production template and removes sleep command.
[#1620](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1620)
> Moves activejob:schedule to production template

- bin/deploy-intensive-worker.sh
Process jobs in the intensive_solr_index queue in the intensive workers.
This will be used to process full text solr indexing at a slower rate to reduce load on Solr.
Management will put solr index jobs that have full text into this queue rather than the default solr index queue.
> Add intensive_solr_index queue to list of queues processed by the intensive workers

- base/Dockerfile
- base/docker-compose.yml
Update docker base from 2.1.0 to 2.3.0
[#2115](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2115)
> Update docker base

- templates/solr-compose.local.yml
Add SOLR_HEAP environment variable to local Solr template.   Allows users to specify a value ('2g') so that the Solr JVM doesn't default to the production size (currently 12g).
> Add SOLR_HEAP environment variable to local Solr template

- .gitignore
- base/Dockerfile
- base/docker-compose.yml
- lib/camerata.rb
- templates/chrome-compose.local.yml
- templates/management-compose.local.yml
This has the advantage of removing chrome from our main image, slimming it down.
Ref https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2073
> M1 Selenium Tests - use an external chrome image

- base/Dockerfile
- base/docker-compose.yml
Upgrades phusion/passenger-ruby27 to version 2.3.1
Related Ticket
[#2295](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2295)
> Upgrade phusion passenger ruby27 version

- Gemfile.lock
- base/Dockerfile
- base/docker-compose.yml
- lib/camerata.rb
Upgrades phusion passenger image to version that includes ruby 3.1.3 and changes ruby version to 3.1.3.  Also addresses [deprecation warnings](https://bugs.webkit.org/show_bug.cgi?id=236684) from `/lib/camerata.rb:368` and updates base image version.
[#2348](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/gh/yalelibrary/yul-dc/2348)
> Upgrades to ruby 3.1.3

- smoke_spec/deploy_spec.rb
Fixes test that was broken in recent deploy attempt.  This changes the expectation to be in line with changes made in blacklight app as part of the Raills upgrade to 6.1
[#2392](https://github.com/orgs/yalelibrary/projects/1/views/1?pane=issue&itemId=20971128)
> Updates expectation

- templates/management-compose.local.yml
Was unable to spin up management due to an issue with the updated key.  Removing the variable allows for management to be spun up again for local development.
> Removes rails master key from local development variables

- templates/blacklight-compose.local.yml
Space breaks API call from BL to Management in local development.
> Remove space from URL in template

- lib/camerata.rb
Newer versions of Docker use `docker compose` instead of `docker-compose`.  This PR updates camerata to use the most current syntax for constructing containers.
> Update docker compose command

- bin/update-continst.sh
Updating the mounts to ones that actually now exist.
Looks like I'll need to redeploy after the merge: https://ci.library.yale.edu/job/DigitalCollections/job/Cluster-Deploy/
Fixes [#2933](https://github.com/yalelibrary/YUL-DC/issues/2933)
> updating nfs flexclones for test and demo

- Gemfile.lock
- camerata.gemspec
Recent release of `concurrent-ruby` has a bug - see issue: https://github.com/rails/rails/pull/54264.  This PR pins the release to the release prior to the bug to prevent errors with logger.
> Pin concurrent ruby

- lib/camerata/secrets.rb
- templates/blacklight-compose.ecs.yml
Updates Solr variables to allow for older releases on production to operate while also using expected values for new Solr instance.  Also, removes hardcoded values from blacklight template that were causing repeated values in params on AWS.
[#2988](https://github.com/yalelibrary/YUL-DC/issues/2988)
> Solr Continuity

- Gemfile.lock
- README.md
- base/README.md
- base/docker-compose.yml
- base/ops/boot.sh
- bin/create-continst.sh
- bin/update-continst.sh
- lib/camerata/version.rb
- templates/blacklight-compose.ecs.yml
- templates/blacklight-compose.local.yml
- templates/blacklight-compose.yml
- templates/db-compose.ecs.yml
- templates/db-compose.local.yml
- templates/db-compose.yml
- templates/iiif-images-compose.ecs.yml
- templates/iiif-images-compose.local.yml
- templates/iiif-images-compose.yml
- templates/intensive-compose.ecs.yml
- templates/intensive-compose.local.yml
- templates/intensive-compose.yml
- templates/management-compose.ecs.yml
- templates/management-compose.local.yml
- templates/management-compose.yml
- templates/solr-compose.ecs.yml
- templates/solr-compose.local.yml
- templates/solr-compose.yml
- templates/worker-compose.ecs.yml
- templates/worker-compose.local.yml
- templates/worker-compose.yml
Removes references to Dynatrace and removes usage.  Also, removes deprecated docker syntax for `version` to eliminate deprecation warnings.
[#3100](https://github.com/yalelibrary/YUL-DC/issues/3100)
> Dynatrace cleanup

- base/Dockerfile
- base/docker-compose.yml
Updates passenger in base image to incorporate Ubuntu 24.04
[#3127](https://github.com/yalelibrary/YUL-DC/issues/3127)
> Updates passenger image for newer version of ubuntu
