- bin/add-alb.sh
- bin/build-cluster.sh
- bin/cluster-ps.sh
- bin/deploy-full.sh
- bin/get-params.sh
- bin/shared-checks.sh
The error checking is verbose and repetative.  Extracting it to a
shared function file makes the scripts a little more legible and
ensures we have consistent error messages across scripts.
> Extract repetitive error checks to a shared function script

- .github_changelog_generator
- CHANGELOG.md
Release newest versions of
* yul-dc-blacklight
* yul-dc-management
* yul-dc-iiif-manifest
> Add a changelog for the v1.6.0 release

- .env
- docker-compose.yml
Connected to https://github.com/yalelibrary/YUL-DC/issues/261
https://github.com/yalelibrary/yul-dc-management/pull/104
> Add Camerata to management dashboard

- .env
- README.md
Add reminder to update camerata version number in `.env`
> Update release process description in README

- README.md
- bin/deploy-main.sh
- bin/deploy-psql.sh
- bin/deploy-solr.sh
connected to https://github.com/yalelibrary/YUL-DC/issues/328
Also detects first deploy of solr and database, adds --enable-service-discovery and --create-log-groups options to ecs-cli compose on first deploy only.  (Adding this to deploy-main is I think just a smidge more complex.)
> Automate retrieving ECS parameters

- docker-compose.ecs.yml
- docker-compose.yml
Connected to https://github.com/yalelibrary/YUL-DC/issues/354
> Pass honeybadger keys to apps (temporary)

- README.md
Updated README with Troubleshooting section.
> updated setup instructions on readme

- README.md
Connected to https://github.com/yalelibrary/YUL-DC/issues/417
> Add moving tickets to release process

- bin/get-params.sh
This PR allows you to set the VPC_ID, SUBNET0 and SUBNET1 environment variables if using an existing vpc and private subnets. Otherwise, it will set those variables from cloudformation.
> get params for Yale's environment

- bin/deploy-psql.sh
- bin/deploy-solr.sh
This PR fixes the deployment of Solr and Postgres to a newly created ECS cluster.
> add check in order to deploy solr and postgres to new cluster

- .circleci/config.yml
- Gemfile.lock
connected to https://github.com/yalelibrary/YUL-DC/issues/487
> Run the full CI suite every 4 hours on master

- .circleci/config.yml
- lib/camerata.rb
- smoke_spec/deploy_spec.rb
Connected to https://github.com/yalelibrary/YUL-DC/issues/486
Co-authored-by: @mlooney
> Schedules smoke test against collections-cd from circleci

- Gemfile.lock
- spec/camerata_cli_spec.rb
update Gemfile.lock for camerata 2.5.4
> Remove outdated test

- templates/db-compose.ecs.yml
- templates/db-compose.local.yml
- templates/db-compose.yml
- templates/iiif-manifest-compose.ecs.yml
- templates/iiif-manifest-compose.local.yml
- templates/iiif-manifest-compose.yml
- fix typos
- remove image info, shouldn't be needed for manifests?
> Add db for iiif-manifest

- templates/iiif-images-compose.yml
- templates/management-compose.yml
This should complete the conversion of the S3_SOURCE_BUCKET_NAME from hard-coded to pulled from SSM
> Pull the S3 source bucket name from SSM for the image service

- smoke_spec/deploy_spec.rb
> Fix typo in smoke test

- Gemfile.lock
- lib/camerata/cluster.rb
- lib/camerata/version.rb
Connected to: https://github.com/yalelibrary/YUL-DC/issues/630
Co-authored by: @kbcarter
> Add IIIF url variables to Camerata parameters code

- base/Dockerfile
- base/README.md
- base/docker-compose.yml
- lib/camerata/secrets.rb
Made a mistake on the previous PR. This PR corrects that mistake.
> Add dynatrace one agent

- base/Dockerfile
- base/README.md
- base/docker-compose.yml
- lib/camerata/secrets.rb
- The current changes don't allow for a successful base build following the directions in the readme. Reverting for now until they are successful.
> Revert build change

- README.md
- base/Dockerfile
- base/README.md
- base/docker-compose.yml
- lib/camerata/secrets.rb
This PR adds Dynatrace OneAgent to the Camerata Base Image, bumps the Image version to 1.1.0 and adds instructions for OneAgent integration
> Dynatrace redo

- lib/camerata.rb
script
* fixed error in naming params  this_cluster -> *args
* removed copypasta from deploy_main
> Fix bug in deploy-main preventing ancillary flags from being passed to

- templates/db-compose.ecs.yml
- templates/db-compose.local.yml
- templates/db-compose.yml
* -c 500 option is now in boot script
> update to use boot script for postgres

- templates/db-compose.local.yml
- templates/db-compose.yml
Update DYNATRACE_TOKEN in postgres templates to keep out of local
> Update templates to keep Dynatrace out of local build

- bin/add-alb.sh
Updates the ALB setup
Connected-to: https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/868
> Update ALB listener rules and update the ALB SSL policy

- bin/add-alb.sh
Remove extra flag that was overriding desired policy.
> remove extra --ssl-policy flag

- templates/solr-compose.ecs.yml
- templates/solr-compose.yml
* chown newly created cores to solr user
* move core init code into boot script for ecs
> Fix for local dev

- smoke_spec/deploy_spec.rb
Also accept blacklight version display with a branch name or version tag.  Connected to https://github.com/yalelibrary/YUL-DC/issues/916
> Update smoke test to reflect current auth method

- templates/management-compose.yml
adds management container command to start activejob schedule
> adds management container command to start activejob schedule

- templates/management-compose.ecs.yml
- templates/management-compose.yml
Reverts yalelibrary/yul-dc-camerata#323
> Revert "Moves activejob:schedule to production template"

- templates/management-compose.ecs.yml
Reverts yalelibrary/yul-dc-camerata#321
> Revert "adds management container command to start activejob schedule"

- base/Dockerfile
- base/docker-compose.yml
worked with @FCRodriguez7 on this. part of https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1813
> update to ubuntu 20.4 base image with ruby 2.7.5

- bin/deploy-worker.sh
Add `large_ptiff` to list of WORKER_QUEUES so that jobs will be processed.
> Adds large_ptiff to list of WORKER_QUEUES

- templates/blacklight-compose.local.yml
Adds chrome to blacklight
[#2073](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/2073)
> Adds chrome to blacklight

- .circleci/config.yml
update docker convenience image
> update convenience image

- lib/camerata/secrets.rb
> Update secrets.rb with SSO-related variables

- Jenkinsfile
- Display the version that was deployed in build description
- Only allow production as an option if the Job Name ends with /Prod-Deploy
- Abort if no version is entered for the thing you are deploying
> Display version in build description

- .circleci/config.yml
- Gemfile.lock
- base/README.md
- base/docker-compose.yml
- camerata.gemspec
- lib/camerata/version.rb
Addresses security related dependabot alerts.
[#2785](https://github.com/yalelibrary/YUL-DC/issues/2785)
> Updates gems

- bin/get-params.sh
> worker resource bump

- Jenkinsfile
- bin/deploy-images.sh
- templates/iiif-images-compose.yml
[2979](https://github.com/yalelibrary/YUL-DC/issues/2979)
> Fix revert deploy stage

- lib/camerata.rb
- lib/camerata/secrets.rb
- templates/blacklight-compose.ecs.yml
- templates/blacklight-compose.local.yml
- templates/blacklight-compose.yml
- templates/intensive-compose.ecs.yml
- templates/intensive-compose.local.yml
- templates/intensive-compose.yml
- templates/management-compose.ecs.yml
- templates/management-compose.local.yml
- templates/management-compose.yml
- templates/worker-compose.ecs.yml
- templates/worker-compose.local.yml
- templates/worker-compose.yml
Pulls out old variable name and replaces it with current syntax
[#2988](https://github.com/yalelibrary/YUL-DC/issues/2988)
> Remove outdated variable and update with current syntax

- smoke_spec/deploy_spec.rb
Updates the public full text parent and child object oids for testing on UAT environment.
[#3045](https://github.com/yalelibrary/YUL-DC/issues/3045)
> Update fulltext objects for UAT

- smoke_spec/deploy_spec.rb
Adds back YCO Fulltext objects to UAT smoke specs
> Updates smoke tests

- Gemfile.lock
- camerata.gemspec
Updates thor to v1.4.0
[#3155](https://github.com/yalelibrary/YUL-DC/issues/3155)
> Update version of thor to v1.4.0
